<#
============================================================================================================================
Module manifest for module: SmartAceDesigns.ScriptoFormTemplates

Generated by: Smart Ace Designs
Generated on: 01/01/2023
============================================================================================================================
#>

@{
RootModule = 'SmartAceDesigns.ScriptoFormTemplates.psm1'
ModuleVersion = '2026.4.0'
CompatiblePSEditions = @('Desktop','Core')
PowerShellVersion = '5.1'
GUID = '99d484e4-d391-4b7e-a45d-1adcfbc2da5b'
Author = 'Smart Ace Designs'
CompanyName = 'Smart Ace Designs'
Copyright = '(c) 2026 Smart Ace Designs. All rights reserved.'
Description = @'
Smart Ace Designs ScriptoForm Templates Module. This module contains a Plaster template and functions used for scaffolding a basic starter ScriptoForm project that a script developer can use to create complex management tools.

A ScriptoForm is a PowerShell script that generates and displays a Microsoft Windows Forms application that can be used for a specific management or system administration task in a computer network environment.
Typically, a ScriptoForm is compiled into an executable file which hides the PowerShell console window during execution and provides a more seamless and familiar experience to the user.

A ScriptoForm project is the set of files and folders, including the PowerShell script, that can be compiled into an executable file using the Microsoft .NET CLI utility (dotnet.exe) which is available with any Microsoft .NET SDK.
'@

PrivateData = @{
    PSData = @{
        ProjectUri = 'https://github.com/Smart-Ace-Designs/SmartAceDesigns.ScriptoFormTemplates'
        LicenseUri = 'https://github.com/Smart-Ace-Designs/SmartAceDesigns.ScriptoFormTemplates/blob/main/LICENSE'
        
        ReleaseNotes = @'
2026.4.0 - April 2026 Release
- Adds support for PowerShell 7.6
- Adds form action wrapper function to facilitate code reuse

2026.1.0 - January 2026 Release
- Adds support for Microsoft .NET 10
- Moves Microsoft .NET 8 to LTS legacy mode

2025.6.0 - June 2025 Release
- Adds template for OTB coding style
- Renames "General" template to "Allman" to indicate the coding style it uses
- Adds parameter to the "New-SADScriptoFormProject" function to allow selection of the coding style template
- Adds OTB style snippets to "powershell.json" file

2025.1.1 - February 2025 Maintenance Release
- Fixes issue with output directory for .NET 9 in README file of template
- Removes "-nologo" option in README file of template

2025.1.0 - January 2025 Release
- Adds support for PowerShell 7.5
- Adds support for Microsoft .NET 9
- Removes support for PowerShell 7.2 (End of support: November 8, 2024)
- Removes support for Microsoft .NET 6 (End of support: November 12, 2024)
- Removes double-space after sentences in markdown files
- Converts template to use SCREAMING_SNAKE_CASE naming convention for settings (aka constants)

2024.6.1 - January 2025 Maintenance Release
- Fixes issue with .gitignore file being excluded from PowerShell Gallery

2024.6.0 - June 2024 Release
- Removes support for PowerShell 7.3 (End of support: May 8, 2024)
- Removes support for Microsoft .NET 7 (End of support: May 28, 2024)

2023.12.0 - December 2023 Release
- Adds support for PowerShell 7.4
- Adds support for Microsoft .NET 8
- Modifies output location for Microsoft .NET 6
- Renames README files to match industry standards (uppercase)

2023.7.0 - July 2023 Release
- Sets mouse to WaitCursor while work is being performed
- Minor white space cleanup in README file
- Fixes terminology used in the module manifest file
- Fixes description in the module manifest file
- Adds release notes to the module manifest file
 
2023.6.0 - June 2023 Release
- Initial release
'@
        
        Tags = @(
                'ScriptoForm',
                'windowsform',
                'form',
                'compile',
                'c#',
                'executable',
                'script-to-executable',
                'script-to-assembly'
        )

        Extensions = @(
            @{
                Module = 'Plaster'
                MinimumVersion = '1.1.4'
                Details = @{TemplatePaths = @('$PSScriptRoot\Templates\General')}
             }
        )
    }
}

RequiredModules = @(@{ModuleName = 'Plaster';ModuleVersion = '1.1.4'})

FunctionsToExport = @('New-SADScriptoFormProject','Build-SADScriptoFormExecutable')
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
}
